name = "MatrixFuns"
uuid = "de0a5e7d-9ed9-4b51-b397-e23faa31cb8d"
authors = ["xquan818 <840169780@qq.com> and contributors"]
version = "1.0.0-DEV"

[deps]
KahanSummation = "8e2b3108-d4c1-50be-a7a2-16352aec75c3"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
